[env:hatchery_weight]
extends = ../../common
board = nodemcuv2
src_dir = src
build_flags =
    -D DEVICE_TYPE="HATCHERY_WEIGHT"
    -D SERVER_URL="https://safal-hatchery.onrender.com/api/weight"
    -D WIFI_SSID="AdvancedCollege"
    -D WIFI_PASS="acem@123"