"""
Generates 5 LaTeX tables for the AI Analytics chapter:
  tab_ai_anomaly_detection.tex
  tab_ai_forecasting_15min.tex
  tab_ai_forecasting_horizons.tex
  tab_ai_risk_distribution.tex
  tab_ai_summary.tex
"""
import os, pandas as pd, numpy as np
os.makedirs('tables', exist_ok=True)

anom_met = pd.read_csv('results/anomaly/metrics.csv')
hc       = pd.read_csv('results/forecast/horizon_comparison.csv')
risk_df  = pd.read_csv('results/risk/risk_scores.csv')

sensor_label = {'temperature':'Temperature','humidity':'Humidity',
                'co2':'CO\\textsubscript{2}','ammonia':'NH\\textsubscript{3}'}

# ── Helper ─────────────────────────────────────────────────────────────────────
def write(path, content):
    with open(path,'w') as f: f.write(content)
    print(f"  written: {path}")

# ── Table 1: Anomaly Detection Performance ─────────────────────────────────────
rows = ""
for _, r in anom_met.iterrows():
    bold_open  = r'{\bfseries ' if r['method']=='Ensemble' else ''
    bold_close = '}' if r['method']=='Ensemble' else ''
    rows += (f"  {bold_open}{r['method']}{bold_close} & "
             f"{r['precision']:.4f} & {r['recall']:.4f} & "
             f"{r['f1_score']:.4f} & {r['false_alarm_rate']:.4f} \\\\\n")

write('tables/tab_ai_anomaly_detection.tex', rf"""% Anomaly Detection Performance Comparison
% Generated by generate_tables.py — do NOT edit manually
\begin{{table}}[htbp]
  \centering
  \caption{{Anomaly detection performance evaluated against known environmental event windows
           (7.1\% of the test set). The ensemble combines Z-Score, Isolation Forest, and LOF
           with a 0.45 soft-voting threshold. Bold row indicates the recommended method.}}
  \label{{tab:ai_anomaly_detection}}
  \begin{{tabular}}{{lcccc}}
    \hline
    \textbf{{Method}} & \textbf{{Precision}} & \textbf{{Recall}} &
    \textbf{{F1-Score}} & \textbf{{False Alarm Rate}} \\
    \hline
{rows}    \hline
  \end{{tabular}}
\end{{table}}
""")

# ── Table 2: Forecasting Performance at 15-min horizon ────────────────────────
hc15 = hc[hc['horizon']==15]
rows = ""
for _, r in hc15.iterrows():
    rows += (f"  {sensor_label.get(r['sensor'],r['sensor'])} & "
             f"{r['MAE']:.4f} & {r['RMSE']:.4f} & "
             f"{r['R2']:.4f} & {r['MAPE']:.3f} \\\\\n")

write('tables/tab_ai_forecasting_15min.tex', rf"""% Forecasting Performance (15-minute horizon)
\begin{{table}}[htbp]
  \centering
  \caption{{Multi-sensor forecasting performance at the 15-minute ahead horizon using a
           Random Forest model with lag features (lags: 1, 2, 3, 5, 10, 15 steps),
           rolling statistics, and time-of-day encoding. Trained on 10\,080 samples
           (7 days at 1-minute resolution).}}
  \label{{tab:ai_forecasting_15min}}
  \begin{{tabular}}{{lcccc}}
    \hline
    \textbf{{Sensor}} & \textbf{{MAE}} & \textbf{{RMSE}} &
    \textbf{{R\textsuperscript{{2}}}} & \textbf{{MAPE (\%)}} \\
    \hline
{rows}    \hline
  \end{{tabular}}
\end{{table}}
""")

# ── Table 3: Horizon comparison ────────────────────────────────────────────────
rows = ""
for h in [15, 30, 60]:
    sub = hc[hc['horizon']==h]
    avg_r2   = sub['R2'].mean()
    avg_mae  = sub['MAE'].mean()
    avg_mape = sub['MAPE'].mean()
    rows += f"  {h} min & {avg_mae:.3f} & {avg_r2:.4f} & {avg_mape:.2f} \\\\\n"

write('tables/tab_ai_forecasting_horizons.tex', rf"""% Forecast Horizon Comparison (averaged across all 4 sensors)
\begin{{table}}[htbp]
  \centering
  \caption{{Average forecasting performance across all four environmental sensors
           (temperature, humidity, CO\textsubscript{{2}}, NH\textsubscript{{3}})
           at three forecast horizons. Performance degrades gracefully with increasing
           horizon, as expected for a lag-feature model.}}
  \label{{tab:ai_forecasting_horizons}}
  \begin{{tabular}}{{lccc}}
    \hline
    \textbf{{Horizon}} & \textbf{{Avg.\ MAE}} &
    \textbf{{Avg.\ R\textsuperscript{{2}}}} & \textbf{{Avg.\ MAPE (\%)}} \\
    \hline
{rows}    \hline
  \end{{tabular}}
\end{{table}}
""")

# ── Table 4: Risk Score Distribution ──────────────────────────────────────────
dist  = risk_df['risk_level'].value_counts()
total = len(risk_df)
rows  = ""
for level in ['Normal','Warning','Critical']:
    cnt = dist.get(level, 0)
    pct = 100*cnt/total
    rows += f"  {level} & {cnt:,} & {pct:.2f} \\\\\n"

write('tables/tab_ai_risk_distribution.tex', rf"""% Risk Score Distribution over 7-day monitoring period
\begin{{table}}[htbp]
  \centering
  \caption{{Distribution of shed health risk levels over the 7-day monitoring period
           (10\,080 one-minute samples). Warning and Critical thresholds are
           composite risk scores of 0.25 and 0.50 respectively, computed as a
           weighted sum across four sensor channels.}}
  \label{{tab:ai_risk_distribution}}
  \begin{{tabular}}{{lcc}}
    \hline
    \textbf{{Risk Level}} & \textbf{{Count}} & \textbf{{Percentage (\%)}} \\
    \hline
{rows}    \hline
    \textit{{Total}} & {total:,} & 100.00 \\
    \hline
  \end{{tabular}}
\end{{table}}
""")

# ── Table 5: AI Analytics Module Summary ──────────────────────────────────────
ens_row   = anom_met[anom_met['method']=='Ensemble'].iloc[0]
avg_r2_15 = hc[hc['horizon']==15]['R2'].mean()
normal_pct= 100*(risk_df['risk_level']=='Normal').sum()/total

write('tables/tab_ai_summary.tex', rf"""% AI Analytics Module Summary
\begin{{table}}[htbp]
  \centering
  \caption{{Summary of the four AI analytics modules implemented as a software extension
           layer on the existing IoT monitoring platform. All modules operate on the
           same four-channel environmental sensor stream (temperature, humidity,
           CO\textsubscript{{2}}, NH\textsubscript{{3}}).}}
  \label{{tab:ai_summary}}
  \begin{{tabular}}{{p{{2.8cm}}p{{3.8cm}}p{{2.8cm}}p{{3.2cm}}}}
    \hline
    \textbf{{Module}} & \textbf{{Method}} & \textbf{{Key Result}} & \textbf{{Dashboard Output}} \\
    \hline
    Anomaly Detection &
      Ensemble (Z-Score + Isolation Forest + LOF) &
      F1 = {ens_row['f1_score']:.4f}; FAR = {ens_row['false_alarm_rate']:.4f} &
      Anomaly score, severity label, sensor explanation \\[4pt]
    Short-Horizon Forecasting &
      Random Forest with lag features &
      Avg.\ R\textsuperscript{{2}} = {avg_r2_15:.4f} (15-min horizon) &
      Predicted sensor values 15--60\,min ahead \\[4pt]
    Risk Scoring &
      Weighted multi-sensor composite index &
      Normal: {normal_pct:.1f}\% of monitoring period &
      Shed Health Risk Index (Normal / Warning / Critical) \\[4pt]
    State Clustering &
      K-Means ($k=4$) on multi-sensor feature space &
      4 distinct operating states identified &
      Environmental state label for pattern recognition \\
    \hline
  \end{{tabular}}
\end{{table}}
""")

print("\nAll 5 tables written to tables/")
