[env:hatchery_sensors]
extends = ../../common       # Inherits from root
board = esp12e
src_dir = src
build_flags =
    -D DEVICE_TYPE=\"HATCHERY_SENSORS\"
lib_deps =
    ${common.lib_deps}
    thingpulse/ESP8266OLED@^4.4.0